urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from sunlightfoundation.com.feeds import NetworkFeed, NetworkOnlyFeed
from sunlightfoundation.presscenter.feeds import PressArticleFeed, PressReleaseFeed
from thefoundation.feeds import BlogFeed
from thefoundation.sitemaps import sitemaps

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^about/funding/$', 'thefoundation.views.funding', name='funding'),
    url(r'^admin/django-lean/', include('django_lean.experiments.admin_urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('wordpress.urls')),
    url(r'^contact/', 'thefoundation.views.contact', name='contact'),
    url(r'^django-lean/', include('django_lean.experiments.urls')),
    url(r'^donate/payment/', include('simplepay.urls')),
    url(r'^donate/', include('sunlightfoundation.donations.urls')),
    url(r'^earmarkdisclosures/', include('sunlightfoundation.earmarkdisclosures.urls')),
    url(r'^f/', include('sunlightfoundation.signups.urls')),
    url(r'^mailinglist/', include('sunlightfoundation.spammer.urls')),
    url(r'^policy/', include('sunlightfoundation.policy.urls')),
    url(r'^press/experts/$', 'django.views.generic.simple.direct_to_template', {"template": "presscenter/experts.html"}),
    url(r'^press/logos/$', 'django.views.generic.simple.direct_to_template', {"template": "presscenter/logos.html"}),
	url(r'^press/', include('sunlightfoundation.presscenter.urls')),
    url(r'^projects/$', 'thefoundation.views.projects', name='projects'),
    url(r'^search/', include('haystack.urls')),
    url(r'^staff/', include('googleauth.urls')),
    url(r'^staff/', include('sunlightfoundation.staff.urls')),
    url(r'^superpacs/', include('sunlightfoundation.superpacs.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^', include('mediasync.urls')),
    url(r'^', include('thefoundation.legacy.urls')),
    url(r'^$', 'thefoundation.views.index', name='index'),
)

# top level navigation redirects
urlpatterns += patterns('django.views.generic.simple',
    #url(r'^blog/',      'redirect_to', {'url': 'http://blog.sunlightfoundation.com/'}),
    url(r'^campaign/',          'redirect_to', {'url': 'http://publicequalsonline.com/'}),
    url(r'^labs/',              'redirect_to', {'url': 'http://sunlightlabs.com/'}),
    url(r'^reporting/',         'redirect_to', {'url': 'http://reporting.sunlightfoundation.com/'}),
    url(r'^people/cjohnson/$',  'redirect_to', {'url': 'http://infovegan.com', 'permanent': True}),
)

# sunlightfoundation.com module
urlpatterns += patterns('sunlightfoundation.com.views',
    url(r'^grants/application/$', 'grant_application', name='grant_application'),
    url(r'^people/$', 'people_index', name='people_list'),
    url(r'^people/(?P<username>[\w-]+)/$', 'people_detail', name="people_detail"),
    url(r'^preview/bumpers/$', 'preview_bumpers', name='preview_bumpers'),
)

# flatpages - migrate from flatpages to static files, temporarily?
urlpatterns += patterns('django.views.generic.simple',
    url(r'^about/$', 'direct_to_template', {"template": "about/index.html"}),
    url(r'^about/board/$', 'direct_to_template', {"template": "about/board.html"}),
    url(r'^about/grants/$', 'direct_to_template', {"template": "about/grants.html"}),
    url(r'^about/history/$', 'direct_to_template', {"template": "about/history.html"}),
    url(r'^policy/poia/about/$', 'direct_to_template', {"template": "policy/poia_about.html"}),
    url(r'^policy/success/$', 'direct_to_template', {"template": "policy/success.html"}),
    url(r'^legal/privacy/$', 'direct_to_template', {"template": "legal/privacy.html"}),
    url(r'^legal/terms/$', 'direct_to_template', {"template": "legal/terms.html"}),
    url(r'^infographics/bluedog-fire-2009/$', 'direct_to_template', {"template": "infographics/bluedog-fire-2009.html"}),
    url(r'^infographics/dodd-shelby/$', 'direct_to_template', {"template": "infographics/dodd-shelby.html"}),
    url(r'^infographics/healthsectorcontributions/$', 'direct_to_template', {"template": "infographics/healthsectorcontributions.html"}),
    url(r'^infographics/reconciliation/$', 'direct_to_template', {"template": "infographics/reconciliation.html"}),
    url(r'^infographics/senate-fire-ag/$', 'direct_to_template', {"template": "infographics/senate-fire-ag.html"}),
    url(r'^infographics/telecom-lobby/$', 'direct_to_template', {"template": "infographics/telecom-lobby.html"}),
    url(r'^infographics/lincoln/energy/$', 'direct_to_template', {"template": "infographics/lincoln_energy.html"}),
    url(r'^join/thankyou/$', 'direct_to_template', {"template": "clean/thankyou.html"}),
    url(r'^live/$', 'direct_to_template', {"template": "live/live.html"}),
    url(r'^live/feedback$', 'direct_to_template', {"template": "live/feedback.html"}),
	url(r'^opengovernmentdirective/$', 'direct_to_template', {"template": "opengovernmentdirective.html"}),
	url(r'^presentations/$', 'direct_to_template', {"template": "presentations/index.html"}),
	url(r'^presentations/emillerMITjune2010/$', 'direct_to_template', {"template": "presentations/emillerMITjune2010.html"}),
	url(r'^projects/2009/earmarks/no_disclosure/$', 'direct_to_template', {"template": "projects/2009/earmarks/no_disclosure.html"}),
	url(r'^projects/2009/expenditures/$', 'direct_to_template', {"template": "projects/2009/expenditures/index.html"}),
	url(r'^projects/2009/healthcare_lobbyist_complex', 'direct_to_template', {"template": "projects/2009/healthcare_lobbyist_complex.html"}),
	url(r'^projects/2009/heart_of_the_matter', 'direct_to_template', {"template": "projects/2009/heart_of_the_matter.html"}),
	url(r'^projects/2009/oogl', 'direct_to_template', {"template": "projects/2009/oogl.html"}),
	url(r'^tmp/heart', 'direct_to_template', {"template": "projects/2009/heart_of_the_matter.html"}),
	url(r'^topics/BP/GulfOilSpill/$', 'direct_to_template', {"template": "topics/BP/GulfOilSpill/index.html"}),
	url(r'^topics/BP/GulfOilSpill/reform/markup/$', 'direct_to_template', {"template": "topics/BP/GulfOilSpill/reform/markup.html"}),
	url(r'^topics/citizensunited', 'direct_to_template', {"template": "topics/citizensunited.html"}),
	url(r'^topics/earmarks', 'direct_to_template', {"template": "topics/earmarks.html"}),
	url(r'^topics/financial-reform', 'direct_to_template', {"template": "topics/financial-reform.html"}),

)

# projects - to be made into a real django app
urlpatterns += patterns('django.views.generic.simple',
    url(r'^projects/congress-for-android/$', 'direct_to_template', {"template": "projects/congress-for-android.html"}),
)

# primary redirects
urlpatterns += patterns('django.views.generic.simple',
    url(r'^android/congress/', 'redirect_to', {'url': '/projects/congress-for-android/'}),
    url(r'^campaigns/$', 'redirect_to', {'url': '/projects/'}),
    url(r'^campaigns/pass482/', 'redirect_to', {'url': 'http://sunlightfoundation.com/pass482/'}),
    url(r'^campaigns/publicequalsonline/', 'redirect_to', {'url': 'http://publicequalsonline.com'}),
    url(r'^campaigns/readthebill/', 'redirect_to', {'url': 'http://readthebill.org'}),
    url(r'^citizensunited/$', 'redirect_to', {'url': '/donate/'}),
    url(r'^contact/thanks/$', 'direct_to_template', {"template": "contact_thanks.html"}),
    url(r'^financial-reform/', 'redirect_to', {'url': '/projects/2010/financial-reform/'}),
    url(r'^grants/application/thanks/$', 'direct_to_template', {"template": "grant_application_thanks.html"}),
    url(r'^grants/minigrantapplication/', 'redirect_to', {'url': '/grants/application/'}),
    url(r'^holiday2008/swfobject.js$', 'direct_to_template', {"template": "projects/2008/holiday2008/swfobject.js", "mimetype": "text/javascript"}),
    url(r'^holiday2008/$', 'direct_to_template', {"template": "projects/2008/holiday2008/index.html"}),
    url(r'^logos/$', 'redirect_to', {'url': '/press/logos/'}),
    url(r'^projects/2006/earmarks/$', 'direct_to_template', {"template": "projects/2006/earmarks/index.html"}),
    url(r'^projects/2007/punchclockmap/$', 'direct_to_template', {"template": "projects/2007/punchclockmap/punchclock.html"}),
    url(r'^projects/2009/expenditures/', 'redirect_to', {'url': '/projects/2009/expenditures/'}), # flatpage
    url(r'^projects/2009/expenditures/totals', 'redirect_to', {'url': '/projects/2009/expenditures/'}), # flatpage
    url(r'^projects/2009/expenditures/committees', 'redirect_to', {'url': '/projects/2009/expenditures/'}), # flatpage
    url(r'^projects/transparency-timeline/$', 'direct_to_template', {"template": "projects/timeline/timeline.html"}),
    # poia
    url(r'^poia/', 'redirect_to', {'url': '/policy/poia/'}),
    url(r'^thepoia/', 'redirect_to', {'url': '/policy/poia/'}),
)

# "mounted" projects
urlpatterns += patterns('',
    url(r'^projects/2007/fortune535/', include('sunlightfoundation.fortune535.urls')),
)


#
# feeds
#

# primary feeds
urlpatterns += patterns('',
    url(r'^feeds/congressional_news/', 'django.views.generic.simple.redirect_to', {'url': 'http://feeds.delicious.com/rss/Sunlight_News_Watch'}),
    url(r'^feeds/blog/$', BlogFeed()),
    url(r'^feeds/latest/$', NetworkFeed()),
    url(r'^feeds/network/$', NetworkOnlyFeed()),
    url(r'^feeds/pressarticles/$', PressArticleFeed()),
    url(r'^feeds/pressreleases/$', PressReleaseFeed()),
)

# feed redirects
urlpatterns += patterns('django.views.generic.simple',
    url(r'^rss.xml', 'redirect_to', {'url': '/feeds/latest/'}),
    url(r'^aggregator/', 'redirect_to', {'url': '/feeds/latest/'}),
    url(r'^atom/feed/', 'redirect_to', {'url': '/feeds/blog/'}),
    url(r'^blog/feed/', 'redirect_to', {'url': '/feeds/blog/'}),
    url(r'^blog/atom/', 'redirect_to', {'url': '/feeds/blog/'}),
    url(r'^feed/sunlightblogs.php', 'redirect_to', {'url': '/feeds/network/'}),
    url(r'^feed/sunlightpressrelease.php', 'redirect_to', {'url': '/feeds/pressreleases/'}),

funding/models.py
from django.db import models
import datetime

def this_year():
    return datetime.datetime.utcnow().year

class Contribution(models.Model):
    year = models.IntegerField(default=this_year)
    contributor = models.CharField(max_length=128)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    note = models.TextField(blank=True)
    
    class Meta:
        ordering = ('-year','-amount','contributor')
    
    def __unicode__(self):
        return u"%s %s $%s" % (self.year, self.contributor, self.amount)

class Grant(models.Model):
    year = models.IntegerField(default=this_year)
    recipient = models.CharField(max_length=128)
    recipient_url = models.URLField(verify_exists=False, blank=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    purpose = models.TextField(blank=True)
    is_minigrant = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-year','-amount','recipient')
        
    def __unicode__(self):
        return u"%s %s $%s" % (self.year, self.recipient, self.amount)

templates/presscenter/base.html
{% extends "base_sidebar.html" %}
{% load media %}

{% block title %}Press - {{ block.super }}{% endblock %}

{% block bodyclass %}press{% endblock %}

{% block sidebar %}
    <div class="module">
    	<nav class="{% block subnavclass %}interiorNav{% endblock %}">
    		<ul>
    			<li class="press"><a href="/press/">Press Center</a></li>
    			<li class="experts"><a href="/press/experts/">Subject Matter Experts</a></li>
    			<li class="releases"><a href="/press/releases/">Press Releases</a></li>
    			<li class="articles"><a href="/press/articles/">Articles &amp; Mentions</a></li>
    			<li class="editorials"><a href="/press/editorials/">Editorials</a></li>
    			<li class="oped"><a href="/press/oped/">Op-Eds</a></li>
    			<li class="webmentions"><a href="/press/webmentions/">Web Mentions</a></li>
    			<li class="logos"><a href="/press/logos/">Logos</a></li>
    		</ul>
    	</nav>
	</div>
	<div class="module">
        <h3 class="withTip">Help Open up Your Government and Get Some Great Stuff While You're at It.</h3>
        <p class="tip">Check out our new tshirts, mug and tote bag on our <a href="http://donate.sunlightfoundation.com/">shopify site</a>.</p>
        <ul id="storeSidebar">
            <li class="withMargin"><a href="http://donate.sunlightfoundation.com/products/caffeinate-me"><img alt="Sunlight Foundation Mug" src={% media_url "images/store_mugSm.jpg" %} /></a></li>
            <li><a href="http://donate.sunlightfoundation.com/products/caffeinate-me"><img alt="Sunlight Foundation Mug Closeup" src={% media_url "images/store_mugSm2.jpg" %} /></a></li>
            <li class="withMargin"><a href="http://donate.sunlightfoundation.com/products/superhero-shirt"><img alt="Sunlight Foundation T-shirt" src={% media_url "images/store_tshirtSm.jpg" %} /></a></li>
            <li><a href="http://donate.sunlightfoundation.com/products/superhero-shirt"><img alt="Sunlight Foundation T-shirt Closeup" src={% media_url "images/store_tshirtSm2.jpg" %} /></a></li>
            <li class="withMargin"><a href="http://donate.sunlightfoundation.com/products/tote"><img alt="Sunlight Foundation Tote" src={% media_url "images/store_toteSm.jpg" %} /></a></li>
            <li><a href="http://donate.sunlightfoundation.com/products/tote"><img alt="Sunlight Foundation Tote Closeup" src={% media_url "images/store_toteSm2.jpg" %} /></a></li>
        </ul>    
        <div class="clear"></div>
    </div>
{% endblock %}

templates/presscenter/index.html
{% extends "presscenter/base.html" %}

{% block subnavclass %}{{ block.super }} press{% endblock %}

{% block content %}

	<h2>Press</h2>

	<div id="sectionContact" class="vcard">
	    <h3>Contact</h3>
	    <img src="http://assets.sunlightfoundation.com/images/blog/avatars/300/300x300_gschneider.jpg" class="section_avatar photo">
	    <div>
	        <a href="/people/gschneider/" class="fn url">Gabriela <br />Schneider</a>
    		<div class="contactDetails">
    		    <span class="title">Communications Director</span>
    		    <span class="tel">(202) 742-1520 ext 236</span>
    		</div>
    	</div>
	</div>
	<div id="sectionContact" class="vcard">
	    <h3>Contact</h3>
	    <img src="http://assets.sunlightfoundation.com/images/blog/avatars/300/300x300_lbartolomeo.jpg" class="section_avatar photo">
	    <div>
	        <a href="/people/lbartolomeo/" class="fn url">Liz<br />Bartolomeo</a>
    		<div class="contactDetails">
    		    <span class="title">Communications Manager</span>
    		    <span class="tel">(202) 742-1520 ext 226</span>
    		</div>
    	</div>
	</div>

	<div class="module docs">
		<h3>Recent Sunlight Foundation Press Releases</h3>
		{% for press_release in press_releases %}
			<article class="poia">
		    	<div class="docs">
		    		<header>
		    			<h4>
							<a href="{{ press_release.get_absolute_url }}">{{ press_release.headline }}</a>
						</h4>
					</header>
					<p>
						<span class="specificBlog">{{ press_release.publication_date|date:"F j, Y" }} </span>&mdash;
						{{ press_release.teaser|safe }}
					</p>
			   	</div>
	    	</article>
		{% endfor %}
		<a href="/presscenter/releases/" class="morelink">All press releases</a>
    </div>
	
    <div class="module docs">
		<h3>Recent Sunlight Foundation Press Articles</h3>
		{% for press_articles in press_articles  %}
			<article class="poia">
			    	<div class="docs {{ press_articles.get_article_type_display }}">
			    		<header>
			    			<h4>
								<a href="{{ press_articles.get_absolute_url }}">{{ press_articles.headline }}</a>
		    
							</h4>
						</header>
						<p>
							<span class="specificBlog">{{ press_articles.publication }} </span>&mdash;
							{{ press_articles.teaser|safe }}
						</p>
				   	</div>
		    </article>
		{% endfor %}
		<a href="/presscenter/articles/" class="morelink">All press mentions</a>
	</div>

{% endblock %}

templates/presscenter/logos.html
{% extends "presscenter/base.html" %}

{% load media %}

{% block title %}Logos - {{ block.super }}{% endblock %}

{% block subnavclass %}{{ block.super }} logos{% endblock %}
{% block content %}

<h2>Logos for Print and Web</h2>
<p>Logos are available in a variety of sizes and formats for use on the web and in print.  </p>

<div class="module">
	<h3 class="logoFor">Sunlight Foundation</h3>   


	<ul class="logo_downloads">
		<li>

			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/SFLogo_whiteText.eps"><img src="{% media_url %}/images/thumbnail_SFLogo_whiteText-1_eps.png" width="100" height="45" alt="Thumbnail SFLogo WhiteText 1 Eps"> 
			</a>

			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/SFLogo_whiteText.eps">White Text Logo EPS
			</a> 
			(postscript)
			

		</li>

		<li>
			<a class="logo_link logo_thumb_container" href="http://assets.sunlightfoundation.com/images/logos/print/SFLogo_blueText.eps"><img src="{% media_url %}/images/thumbnail_SFLogo_blueText_eps.png" width="100" height="45" alt="Thumbnail SFLogo BlueText Eps">
			</a>

			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/SFLogo_blueText.eps">Blue text Logo EPS
			</a> 
			(postscript) 
		</li>

		<li>
			<a class="logo_link logo_thumb_container" href="http://assets.sunlightfoundation.com/images/logos/print/sunlight_large_for_print.gif"><img src="{% media_url %}/images/thumbnail_sunlight_large_for_print.gif" width="100" height="47" alt="Thumbnail Sunlight Large For Print">
			</a>

			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlight_large_for_print.gif">Large GIF
			</a>
			(1500 x 680)
		</li> 

		<li>
			<a  class="logo_link logo_thumb_container" href="http://assets.sunlightfoundation.com/images/logos/print/sunlight_bw_2000x900.gif"><img src="{% media_url %}/images/thumbnail_sunlight_bw_2000x900.jpg" width="100" height="47" alt="Thumbnail Sunlight Bw 2000x900">
			</a>

			<a  class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlight_bw_2000x900.gif">B/W GIF
			</a> 
			(2000 x 900)
		</li>   
 
		<li>
			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/web/sflogo_bluebg_550x315.gif"><img src="{% media_url %}/images/thumbnail_sflogo_bluebg_550x315.jpg" width="100" height="57" alt="Thumbnail Sflogo Bluebg 550x315">
			</a>
			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/web/sflogo_bluebg_550x315.gif">Blue Background, white text GIF
			</a> 
			(550 x 315) 
		</li>

		<li>
			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/web/SFLogo_whitebg_500wide.gif"><img src="{% media_url %}/images/thumbnail_SFLogo_whitebg_500wide.jpg" width="100" height="45" alt="Thumbnail SFLogo Whitebg 500wide">
			</a>
			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/web/SFLogo_whitebg_500wide.gif">
			White Background, blue text GIF
			</a> 
			(500 x 227)
		</li>

	</ul>
	<div class="clear"></div>

	<h3 class="logoFor">Sunlight Labs</h3> 
	<ul class="logo_downloads">
		<li>
			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightLabs_logos_outlines.eps"><img src="{% media_url %}/images/thumbnail_sunlightLabs_logos_outlines-1_eps.png" width="100" height="73" alt="Thumbnail SunlightLabs Logos Outlines 1 Eps">
			</a>
			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightLabs_logos_outlines.eps">Sunlight Labs logo
			</a> (EPS)
		</li>
	</ul>


	<div class="clear"></div>

	<h3 class="logoFor">Campaigns</h3>
	<ul class="logo_downloads">
		<li>

			<a class="logo_link" href="http://assets.publicequalsonline.com/logos/public_equals_online_logo.eps">Public Equals Online EPS
			</a> 
			(postscript)
		</li>
	</ul>


	<div class="clear"></div>

	<h3 class="logoFor">Contests</h3>
	<ul class="logo_downloads">
		<li>
			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/design_for_america_logo.eps"><img src="{% media_url %}/images/thumbnail_design_for_america_logo_eps.png" width="100" height="24" alt="Thumbnail Design For America Logo Eps">
			</a>
			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/design_for_america_logo.eps">Design For America EPS
			</a>(postscript)
		</li>

		<li>
			<a class="logo_thumb_container logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightfoundation_apps_for_america.eps"><img src="{% media_url %}/images/thumbnail_sunlightfoundation_apps_for_america_eps.png" width="100" height="30" alt="Thumbnail Sunlightfoundation Apps For America Eps">
			</a>
			<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightfoundation_apps_for_america.eps">Apps for America EPS
			</a> (postscript)
		</li>
	</ul>


<div class="clear"></div>



<h3 class="logoFor">Events</h3> 
<ul class="logo_downloads">
<li>
<div class="logo_thumb_container">
<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightfoundation_transparency_camp.eps"><img src="{% media_url %}/images/thumbnail_sunlightfoundation_transparency_camp_eps.png" width="100" height="31" alt="Thumbnail Sunlightfoundation Transparency Camp Eps"></a></div>
<a class="logo_link" href="http://assets.sunlightfoundation.com/images/logos/print/sunlightfoundation_transparency_camp.eps">Transparency Camp EPS</a> (postscript)</li>
</ul>
<div class="clear"></div>
</div>



{% endblock %}

templates/presscenter/navigation.html
<div id="press_nav_box">
	<p class="tip">Looking for something else? Browse our archives by date.</p>
	<form action="/press/" method="post" id="press-nav-form">
		{% csrf_token %}
		{{ press_nav_form.pub_type }}
		<ul class="press_year_navigation">
			<li class="press_year">
				<label for="id_year">{{ press_nav_form.year.label }}</label>
				{{ press_nav_form.year }}
			</li>
			<li  class="press_month_navigation">
				<label for="id_month">{{ press_nav_form.month.label }}</label>
				{{ press_nav_form.month }}
			</li>
			<li>
				<button type="submit" name="submit-btn" class="press_nav_button"><span>Submit</span>
			</li>
		</ul>
	</form>
	<div class="clear"></div>
</div>

templates/presscenter/pressarticle_archive.html
{% extends "presscenter/base.html" %}
{% load press %}
{% load pagination_tags %}

{% block title %}Press Articles &amp; Mentions - {{ block.super }}{% endblock %}

{% block subnavclass %}{{ block.super }} {{ pub_type }}{% endblock %}

{% block content %}
 
	{% if only_editorials %}
		<h2>Press Editorials</h2>
	{% else %}
		{% if only_oped %}
			<h2>Op-Eds</h2>
		{% else %}	
			<h2>Press Articles &amp; Mentions Archives</h2>
			{% endif %}
	{% endif %}
	

    {% include "presscenter/navigation.html" %}

	{% if latest %}
	<div class="module docs">
		{% if only_editorials %}
			<h3>Recent Press Editorials</h3>
		{% else %}
			{% if only_oped %}
				<h3>Recent Op-Eds</h3>
			{% else %}
				<h3>Recent Press Articles &amp; Mentions</h3>	
			{% endif %}	
		{% endif %}	
	
		
		
			{% for object in latest %}
		<article class="poia">
		    	<div class="press_article {{ object.get_article_type_display }}">
		    		<header>
		    			<h4>
							<a href="{{ object.get_absolute_url }}">{{ object.headline }}</a>

						</h4>
					</header>
					<p>
						<span class="specificBlog">{{ object.publication }} </span>&mdash;
						{{ object.teaser|safe }}
					</p>
			   	</div>
	    </article>
			{% endfor %}
		
		
				
	</div>	
	{% endif %}

	{% paginate %}

{% endblock %}

templates/presscenter/pressarticle_archive_day.html
{% extends "presscenter/base.html" %}
{% load press %}
{% load pagination_tags %}

{% block title %}{{ day|date:"F j, Y" }} Press Articles &amp; Mentions - {{ block.super }}{% endblock %}

{% block subnavclass %}{{ block.super }} {{ pub_type }}{% endblock %}

{% block content %}

	{% if only_editorials %}
		<h2>Press Editorials</h2>
	{% else %}	
		<h2>Press Articles &amp; Mentions Archives</h2>
	{% endif %}
	
    {% include "presscenter/navigation.html" %}

	{% if object_list %}
		<ul>
			{% for object in object_list %}
				<li class="{{ object.get_article_type_display }}">
					<h3><a href="{{ object.get_absolute_url }}">{{ object.publication }} - {{ object.headline }}</a></h3>
					<p>{{ object.teaser|safe }}</p>
				</li>
			{% endfor %}
		</ul>
	{% endif %}

	{% paginate %}
	
{% endblock %}

templates/presscenter/pressarticle_archive_print.html
{% extends "print.html" %}

{% block title %}{{ object.headline }}{% endblock %}

{% block subnavclass %}{{ block.super }} {{ pub_type }}{% endblock %}

{% block content %}

	<article>
		
		<header>
			<hgroup>
			    <h1>{{ object.headline }}</h1>
			    {% if object.sub_headline %}
					<h2>{{ object.sub_headline }}</h2>
				{% endif %}
			</hgroup>
		    <p>Publication: <a href="{{object.url}}">{{ object.publication }}</a></p>
			<p>{{ object.author }}{% if object.publication_date %}<br />{{ object.publication_date|date:"F j, Y" }}{% endif %}</p>
		</header>

		{% if object.from_drupal %}
			{{ object.body|safe }}    
		{% else %}
			{% autoescape off %}{{ object.body|linebreaks }}{% endautoescape %}
		{% endif %}

	</article>

{% endblock %}